In [6]:
import numpy as np

In [9]:
np.__version__

'2.2.6'

In [16]:
import sys
sys.version

'3.13.3 (tags/v3.13.3:6280bb5, Apr  8 2025, 14:47:33) [MSC v.1943 64 bit (AMD64)]'

## Creating List

In [17]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [18]:
type(my_list)

list

## List To Array

In [28]:
print(np.array([12,29,19,28,209]))
print(type(np.array([12,29,19,28,209])))

[ 12  29  19  28 209]
<class 'numpy.ndarray'>


In [20]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [24]:
print(arr)
print('Type of my_list :',type(my_list))
print('Type of arr :',type(arr))

[0 1 2 3 4 5]
Type of my_list : <class 'list'>
Type of arr : <class 'numpy.ndarray'>


In [30]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [32]:
np.arange(9)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [36]:
np.arange(0,5)  

array([0, 1, 2, 3, 4])

In [39]:
np.arange(10,20) # Value between 10 to 20

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
np.arange(20,10) # First argument should be less than second arguments

array([], dtype=int64)

In [43]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [45]:
np.arange(-16,10)

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [46]:
np.arange(10,10)

array([], dtype=int64)

In [47]:
np.arange(10,30,5) # 5 is the step count

array([10, 15, 20, 25])

In [49]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [54]:
np.zeros(10) # Create a array of zero 
# Parameter tunning

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [64]:
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [66]:
np.zeros(5,dtype=int) # Hyperparameter  tunning

array([0, 0, 0, 0, 0])

In [75]:
# 2 diamentional array
arr = np.zeros((2,2),dtype=int)
print(arr)
print(f'arr is the {np.ndim(arr)} diamentional array')

[[0 0]
 [0 0]]
arr is the 2 diamentional array


In [70]:
zero = np.zeros([2,2])
print(zero)
print(type(zero))

[[0. 0.]
 [0. 0.]]
<class 'numpy.ndarray'>


In [79]:
np.zeros((2,10)) # Here the 2 is row and 10 is column

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
n = np.zeros((10,10),dtype=int)
print(n)
print(type(n))
print(np.ndim(n))


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
<class 'numpy.ndarray'>
2


In [89]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [91]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [96]:
np.two((2,3))

AttributeError: module 'numpy' has no attribute 'two'

In [97]:
np.three(2,3)

AttributeError: module 'numpy' has no attribute 'three'

In [98]:
rand(2,3)

NameError: name 'rand' is not defined

In [99]:
random.rand(3,2)

NameError: name 'random' is not defined

In [100]:
np.random.rand(3,2)

array([[0.85745668, 0.48829072],
       [0.75819012, 0.55133986],
       [0.75955594, 0.77575752]])

In [105]:
np.random.rand(5) # it generate 5 randon number which is float

array([0.22722011, 0.68302037, 0.55615058, 0.19049201, 0.00183379])

In [102]:
np.rand(4)

AttributeError: module 'numpy' has no attribute 'rand'

In [103]:
np.random.rand(3,5)

array([[0.13703787, 0.08357202, 0.23353605, 0.2257795 , 0.79120222],
       [0.53565481, 0.94702539, 0.49325727, 0.25529001, 0.04688171],
       [0.36176941, 0.1023086 , 0.34372092, 0.42334148, 0.23768487]])

In [106]:
np.random.randint(13) # it generate a random single number in between0 to 13 

11

In [109]:
np.random.randint(4,6) # Generate a random number between 4 to 5

5

In [111]:
np.random.randint(2,20,4) # Generate 4 random number between 2 to 20

array([11, 19, 19, 17], dtype=int32)

In [126]:
np.random.randint(0,1)

0

In [127]:
np.random.randint(10,20,5)

array([16, 12, 10, 12, 15], dtype=int32)

In [128]:
np.random.randint(123,189,100)

array([164, 171, 165, 144, 159, 180, 132, 170, 147, 136, 152, 124, 165,
       149, 184, 178, 135, 148, 169, 157, 157, 182, 166, 145, 140, 128,
       160, 140, 134, 162, 160, 187, 143, 135, 150, 146, 188, 137, 125,
       154, 123, 181, 176, 145, 166, 158, 186, 137, 168, 188, 160, 183,
       156, 164, 174, 123, 148, 144, 174, 143, 124, 123, 163, 129, 126,
       148, 173, 148, 174, 150, 137, 134, 165, 144, 154, 159, 143, 180,
       188, 141, 151, 141, 142, 175, 168, 137, 142, 141, 163, 143, 183,
       154, 154, 159, 129, 124, 166, 175, 188, 174], dtype=int32)

In [129]:
np.arange(1,13).reshape(12,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [132]:
x =np.random.randint(10,20,(5,4))
x

array([[10, 11, 19, 12],
       [11, 13, 12, 13],
       [16, 13, 14, 13],
       [15, 13, 14, 19],
       [16, 19, 17, 16]], dtype=int32)

In [135]:
x[0,1]

np.int32(11)